Changed styling methods, regex keyword recognition, speedups and more
platformer/typst-algorithms pull request #15
Opened 2023-12-19 01:23 UTC by ludwig-austermann

Ok after some time — here my implementation, where
- `strong-keywords` was removed in favour of `keyword-styles`
- `keyword-styles`, `main-text-styles` and `comment-styles` are now parameters accepting functions from `content -> content`
- `line-number-styles` is a parameter accepting a function `int -> content`
- `keywords` now also accepts items of type `regex` and have special behaviour depending on if non-word characters are in front or at the back of them
- some for loops with array pushing were changed to direct `map` calculation, making calculations more efficient
- `no-emph` was changed to `no-keyword`

I think the code is now better readable, except when having applied the loop conversions. Tests, examples and documentation was added/changed.

- [ ] In two places I commented some code out, because I think, that it is redundant — it should hence be removed before accepting.

2023-12-19 01:27 UTC, ludwig-austermann commented on algo.typ
> +  // TODO: WHY?!
As far as I understand, taking the width directly has no different behaviour, or am I overseeing some weird special case?

2023-12-20 01:52 UTC, platformer requested changes
The changes mostly look good, just some small things to address. I think making better use of array functions is a good idea.

2023-12-20 01:52 UTC, platformer commented on algo.typ
> +  // TODO: WHY?!
same comment as with `_algo-indent-guides`

2023-12-20 01:52 UTC, platformer commented on test/test.typ
>  #code(
This test seems to have failed. But if you can't figure it out, don't bang your head over it. The approach used for `code` is currently outdated, and this is a niche test case anyway. Yet another thing to update when improved tables arrive.

2023-12-20 01:52 UTC, platformer commented on typst.toml
> +exclude = ["test", "examples/seperated"]
This line isn't actually necessary. I only ever upload the minimally necessary files when updating the package.

2023-12-20 01:52 UTC, platformer commented on test/test.typ
> +#algo(
I'd also like to test the simple case of a multi-word keyword with no special characters on the end, just to make sure it's working. i.e. if `keywords` includes `"hello world"`:

```typst
...
blah hello world blah // hello world is highlighted
blahhello world blah // no highlight
blah hello worldblah // no highlight
...
```

2023-12-20 01:52 UTC, platformer commented on test/test.typ
> +  "keywords:", `("A", "B\*", "\*C", "\*D\*", "\+", "E\*E", "FF?F", "G{4}")`,
Make sure to update this. Later I'll rewrite this document to use idwtet, but unfortunately it wasn't available at the time I was making this.

2024-10-15 00:31 UTC, closed without merging